import { createClient } from '@sanity/client'

const client = createClient({
  projectId: '73xn8klv',
  dataset: 'production',
  apiVersion: '2024-01-01',
  useCdn: false,
  token: process.env.SANITY_WRITE_TOKEN,
})

const songs = [
  { title: { en: 'Canon in D', 'zhTW': 'D大調卡農', 'zhCN': 'D大调卡农', ja: 'カノン', ko: '캐논', fr: 'Canon en ré majeur', de: 'Kanon in D-Dur' }, composer: { en: 'Pachelbel', 'zhTW': '帕海貝爾', 'zhCN': '帕赫贝尔', ja: 'パッヘルベル', ko: '파헬벨', fr: 'Pachelbel', de: 'Pachelbel' }, year: 1680, genre: 'Classical', era: 'Baroque', performances: 2, description: { en: 'One of the most famous classical pieces ever written, Pachelbel\'s Canon features three violins playing a canon over a ground bass. Rediscovered in the 20th century, it has become a wedding staple worldwide.', 'zhTW': '史上最著名的古典樂曲之一。帕海貝爾的卡農以三把小提琴在固定低音上演奏卡農。20世紀重新被發掘後，成為全球婚禮必備曲目。', 'zhCN': '史上最著名的古典乐曲之一。帕赫贝尔的卡农以三把小提琴在固定低音上演奏卡农。20世纪重新被发掘后，成为全球婚礼必备曲目。', ja: '最も有名な古典曲の一つ。パッヘルベルのカノンは、3本のヴァイオリンがグラウンドバスの上でカノンを奏でる。20世紀に再発見され、世界中の結婚式で欠かせない曲となった。', ko: '가장 유명한 클래식 곡 중 하나로, 파헬벨의 캐논은 세 대의 바이올린이 그라운드 베이스 위에서 캐논을 연주합니다. 20세기에 재발견되어 전 세계 결혼식에서 빠질 수 없는 곡이 되었습니다.', fr: 'L\'une des pièces classiques les plus célèbres jamais écrites. Le Canon de Pachelbel met en scène trois violons jouant un canon sur une basse obstinée. Redécouvert au XXe siècle, il est devenu un incontournable des mariages dans le monde entier.', de: 'Eines der berühmtesten klassischen Stücke, die je geschrieben wurden. Pachelbels Kanon zeigt drei Violinen, die einen Kanon über einem Ground Bass spielen. Im 20. Jahrhundert wiederentdeckt, ist es weltweit zu einem Hochzeitsklassiker geworden.' } },
  { title: { en: '月亮代表我的心', 'zhTW': '月亮代表我的心', 'zhCN': '月亮代表我的心', ja: '月亮代表我的心（ムーン・リプレゼンツ・マイ・ハート）', ko: '월량대표아적심', fr: 'La Lune représente mon cœur', de: 'Der Mond repräsentiert mein Herz' }, composer: { en: '翁清溪 / 孫儀', 'zhTW': '翁清溪 / 孫儀', 'zhCN': '翁清溪 / 孙仪', ja: '翁清溪 / 孫儀', ko: '웡칭시 / 쑨이', fr: 'Weng Qingxi / Sun Yi', de: 'Weng Qingxi / Sun Yi' }, year: 1972, genre: 'Chinese Pop', era: '20th Century', performances: 2, description: { en: 'Originally sung by 陳芬蘭 in 1972, this song became a global Chinese classic when Teresa Teng rerecorded it in 1977. It remains one of the most covered Chinese songs of all time.', 'zhTW': '原唱陳芬蘭於1972年發行，1977年鄧麗君重新詮釋後成為全球華人經典。至今仍是翻唱次數最多的中文歌曲之一。', 'zhCN': '原唱陈芬兰于1972年发行，1977年邓丽君重新诠释后成为全球华人经典。至今仍是翻唱次数最多的中文歌曲之一。', ja: '1972年に陳芬蘭が歌い、1977年にテレサ・テンが再録音して世界的な中国の名曲となった。今なお最もカバーされた中国語曲の一つである。', ko: '1972년 천펀란이 부른 이 노래는 1977년 테레사 텡이 다시 녹음하면서 전 세계 중국인의 클래식이 되었습니다. 지금까지도 가장 많이 커버된 중국 노래 중 하나입니다.', fr: 'Initialement chantée par 陳芬蘭 en 1972, cette chanson est devenue un classique chinois mondial lorsque Teresa Teng l\'a réenregistrée en 1977. Elle reste l\'une des chansons chinoises les plus reprises de tous les temps.', de: 'Ursprünglich 1972 von 陳芬蘭 gesungen, wurde dieses Lied zu einem globalen chinesischen Klassiker, als Teresa Teng es 1977 neu aufnahm. Es bleibt eines der am meisten gecoverten chinesischen Lieder aller Zeiten.' } },
  { title: { en: '望春風', 'zhTW': '望春風', 'zhCN': '望春风', ja: '望春風（バンチュンフォン）', ko: '망춘풍', fr: 'Espérer la brise printanière', de: 'Auf die Frühlingsbrise warten' }, composer: { en: '鄧雨賢 / 李臨秋', 'zhTW': '鄧雨賢 / 李臨秋', 'zhCN': '邓雨贤 / 李临秋', ja: '鄧雨賢 / 李臨秋', ko: '덩위셴 / 리린추', fr: 'Deng Yuxian / Li Linqiu', de: 'Deng Yuxian / Li Linqiu' }, year: 1933, genre: 'Taiwanese Folk', era: 'Early 20th Century', performances: 1, description: { en: 'A iconic Taiwanese folk song composed during Japanese rule. Its pentatonic melody captures the beauty of a young woman\'s longing for love. Voted #1 most beloved oldie in Taiwan.', 'zhTW': '日治時期創作的經典台灣民謠。五聲音階旋律捕捉少女對愛情的含蓄嚮往。曾被票選為台灣最受歡迎的老歌第一名。', 'zhCN': '日治时期创作的经典台湾民谣。五声音阶旋律捕捉少女对爱情的含蓄向往。曾被票选为台湾最受欢迎的老歌第一名。', ja: '日本統治時代に作曲された象徴的な台湾民謡。五音音階の旋律が、愛を切望する乙女心の美しさを捉えている。台湾で最も愛される時代を超えた名曲第1位に選ばれた。', ko: '일본 통치 시대에 작곡된 상징적인 대만 민요입니다. 오음 음계의 선율이 사랑을 갈망하는 젊은 여성의 아름다움을 담아냅니다. 대만에서 가장 사랑받는 올드송 1위로 선정되었습니다.', fr: 'Une chanson folklorique taïwanaise emblématique composée sous la domination japonaise. Sa mélodie pentatonique capture la beauté du désir d\'amour d\'une jeune femme. Élue chanson ancienne préférée n°1 à Taïwan.', de: 'Ein ikonischer taiwanesischer Volkssong, komponiert während der japanischen Herrschaft. Seine pentatonische Melodie fängt die Schönheit der Sehnsucht einer jungen Frau nach Liebe ein. Zum beliebtesten Oldie Nr. 1 in Taiwan gewählt.' } },
  { title: { en: '明天會更好', 'zhTW': '明天會更好', 'zhCN': '明天会更好', ja: '明天會更好（明るい明日）', ko: '명천회경호', fr: 'Demain sera meilleur', de: 'Morgen wird es besser' }, composer: { en: '羅大佑', 'zhTW': '羅大佑', 'zhCN': '罗大佑', ja: '羅大佑', ko: '뤄다유', fr: 'Lo Ta-yu', de: 'Lo Ta-yu' }, year: 1985, genre: 'Chinese Pop', era: '20th Century', performances: 1, description: { en: 'Taiwan\'s answer to \'We Are the World\', this charity single brought together 60 artists. Its message of hope resonates across generations.', 'zhTW': '台灣版的《We Are the World》，這首慈善單曲匯集了60位歌手。希望的信息跨越世代共鳴。', 'zhCN': '台湾版的《We Are the World》，这首慈善单曲汇集了60位歌手。希望的信息跨越世代共鸣。', ja: '台湾版「ウィ・アー・ザ・ワールド」とも言えるこのチャリティーシングルには60人のアーティストが集結。希望のメッセージは世代を超えて共鳴している。', ko: '대만의 \'We Are the World\'라고 불리는 이 자선 싱글에는 60명의 아티스트가 참여했습니다. 희망의 메시지는 세대를 초월하여 공감을 얻고 있습니다.', fr: 'La réponse taïwanaise à \'We Are the World\', ce single caritatif a réuni 60 artistes. Son message d\'espoir résonne à travers les générations.', de: 'Taiwans Antwort auf \'We Are the World\', diese Wohltätigkeitssingle brachte 60 Künstler zusammen. Ihre Botschaft der Hoffnung hallt über Generationen hinweg nach.' } },
  { title: { en: 'River Flows in You', 'zhTW': 'River Flows in You', 'zhCN': 'River Flows in You', ja: 'River Flows in You', ko: 'River Flows in You', fr: 'River Flows in You', de: 'River Flows in You' }, composer: { en: 'Yiruma (이루마)', 'zhTW': '李閏珉 (Yiruma)', 'zhCN': '李闰珉 (Yiruma)', ja: 'イルマ (Yiruma)', ko: '이루마 (Yiruma)', fr: 'Yiruma (이루마)', de: 'Yiruma (이루마)' }, year: 2001, genre: 'Contemporary Classical', era: '21st Century', performances: 1, description: { en: 'Yiruma\'s most famous piano piece, inspired by Riverdance. Gained worldwide fame after being featured in Twilight. A modern piano classic.', 'zhTW': '李閏珉最著名的鋼琴曲，靈感來自《Riverdance》。因《暮光之城》採用而全球爆紅。現代鋼琴經典。', 'zhCN': '李闰珉最著名的钢琴曲，灵感来自《Riverdance》。因《暮光之城》采用而全球爆红。现代钢琴经典。', ja: 'イルマの最も有名なピアノ曲で、『リバーダンス』に触発された。『トワイライト』で使用されて世界的な名声を得た。現代ピアノの古典。', ko: '이루마의 가장 유명한 피아노곡으로, 리버댄스에서 영감을 받았습니다. \'트와일라잇\'에 사용되면서 세계적인 명성을 얻었습니다. 현대 피아노 클래식입니다.', fr: 'La pièce pour piano la plus célèbre de Yiruma, inspirée par Riverdance. A acquis une renommée mondiale après avoir été présentée dans Twilight. Un classique moderne du piano.', de: 'Yirumas berühmtestes Klavierstück, inspiriert von Riverdance. Erlangte weltweite Berühmtheit, nachdem es in Twilight verwendet wurde. Ein moderner Klavierklassiker.' } },
  { title: { en: '如願', 'zhTW': '如願', 'zhCN': '如愿', ja: '如願（願い通りに）', ko: '여원', fr: 'Comme souhaité', de: 'Wie gewünscht' }, composer: { en: '錢雷 / 唐恬', 'zhTW': '錢雷 / 唐恬', 'zhCN': '钱雷 / 唐恬', ja: '錢雷 / 唐恬', ko: '첸레이 / 탕티엔', fr: 'Qian Lei / Tang Tian', de: 'Qian Lei / Tang Tian' }, year: 2021, genre: 'Chinese Pop', era: '21st Century', performances: 1, description: { en: 'Performed by Faye Wong for the film \'My Country, My Parents\'. Won multiple awards and became an anthem of跨generational传承.', 'zhTW': '王菲為電影《我和我的父輩》演唱。榮獲多項大獎，成為跨世代傳承的代表作。', 'zhCN': '王菲为电影《我和我的父辈》演唱。荣获多项大奖，成为跨世代传承的代表作。', ja: 'フェイ・ウォンが映画『マイ・カントリー・マイ・ペアレンツ』のために歌唱。複数の賞を受賞し、世代を超えた継承のアンセムとなった。', ko: '페이 왕이 영화 \'마이 컨트리, 마이 페어런츠\'를 위해 불렀습니다. 여러 상을 수상하고 세대를 초월한 계승의 국가가 되었습니다.', fr: 'Interprétée par Faye Wong pour le film \'My Country, My Parents\'. A remporté plusieurs prix et est devenue un hymne de transmission intergénérationnelle.', de: 'Gesungen von Faye Wong für den Film \'My Country, My Parents\'. Gewann mehrere Preise und wurde zu einer Hymne der generationenübergreifenden Weitergabe.' } },
  { title: { en: 'golden hour', 'zhTW': 'golden hour', 'zhCN': 'golden hour', ja: 'golden hour', ko: 'golden hour', fr: 'golden hour', de: 'golden hour' }, composer: { en: 'JVKE', 'zhTW': 'JVKE', 'zhCN': 'JVKE', ja: 'JVKE', ko: 'JVKE', fr: 'JVKE', de: 'JVKE' }, year: 2022, genre: 'Pop', era: '21st Century', performances: 1, description: { en: 'JVKE\'s breakout hit that went viral on TikTok. A dreamy piano ballad about young love, inspired by Franz Liszt and Frank Ocean.', 'zhTW': 'JVKE 在 TikTok 爆紅的突破單曲。關於青春愛情的夢幻鋼琴情歌，靈感來自李斯特和 Frank Ocean。', 'zhCN': 'JVKE 在 TikTok 爆红的突破单曲。关于青春爱情的梦幻钢琴情歌，灵感来自李斯特和 Frank Ocean。', ja: 'TikTokで話題になったJVKEのブレイクヒット。フランツ・リストとフランク・オーシャンに触発された、若い恋についての夢のようなピアノバラード。', ko: 'TikTok에서 입소문을 탄 JVKE의 획기적인 히트곡입니다. 프란츠 리스트와 프랭크 오션에게서 영감을 받은 젊은 사랑에 대한 몽환적인 피아노 발라드입니다.', fr: 'Le tube révolutionnaire de JVKE devenu viral sur TikTok. Une ballade pianistique rêveuse sur l\'amour jeune, inspirée par Franz Liszt et Frank Ocean.', de: 'JVKEs bahnbrechender Hit, der auf TikTok viral ging. Eine verträumte Klavierballade über junge Liebe, inspiriert von Franz Liszt und Frank Ocean.' } },
  { title: { en: '繼續走', 'zhTW': '繼續走', 'zhCN': '继续走', ja: '繼續走（歩き続ける）', ko: '계속 걸어가다', fr: 'Continuer à marcher', de: 'Weitergehen' }, composer: { en: '瑞Rui', 'zhTW': '瑞Rui', 'zhCN': '瑞Rui', ja: '瑞Rui', ko: '瑞Rui', fr: 'Rui', de: 'Rui' }, year: 2025, genre: 'Original', era: '21st Century', performances: 1, description: { en: 'Original composition by band member 瑞Rui. Created through the \'Three Notes to a Song\' challenge. A testament to our band\'s creative spirit.', 'zhTW': '團員瑞Rui的原創作品。透過「三個音寫一首歌」挑戰創作而成。展現樂團創作精神的代表作。', 'zhCN': '团员瑞Rui的原创作品。通过「三个音写一首歌」挑战创作而成。展现乐团创作精神的代表作。', ja: 'バンドメンバー瑞Ruiによるオリジナル曲。「3つの音から曲を作る」チャレンジを通じて生まれた。バンドの創造性の証。', ko: '밴드 멤버 瑞Rui의 오리지널 작곡입니다. \'세 개의 음으로 노래 만들기\' 챌린지를 통해 탄생했습니다. 밴드의 창조적 정신을 보여주는 증거입니다.', fr: 'Composition originale du membre du groupe 瑞Rui. Créée dans le cadre du défi \'Trois notes pour une chanson\'. Un témoignage de l\'esprit créatif de notre groupe.', de: 'Originalkomposition von Bandmitglied 瑞Rui. Entstanden durch die \'Drei Noten zu einem Lied\'-Herausforderung. Ein Zeugnis des kreativen Geistes unserer Band.' } },
]

async function main() {
  console.log(`Creating ${songs.length} songs...`)
  for (const song of songs) {
    const result = await client.create({ _type: 'song', ...song })
    console.log(`Created: ${song.title.en} (${result._id})`)
  }
  console.log('Done!')
}

main().catch(console.error)
